name: simon smith
favicon: null
layout_spectrum: 0.12308
typography_spectrum: 0.5007
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#1b1b1b'
    - '#fbfbfb'
    - '#464646'
    - '#c7c7c7'
    - '#8b8b8b'
  brandStrength: 0
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
